# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'Test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'KakaJSON', '~> 1.1.2'

  # Pods for Test

end
