platform :ios, '10.0'

# 使用动态库
use_frameworks!

target 'SwiftLearn' do
  
  pod 'MJExtension', '3.2.2'
  pod 'MJRefresh', '3.5.0'

  pod 'SnapKit', '~> 5.0.0'
  
  # pod 'TYAttributedLabel', '~> 2.6.2' // 网络上下不了，直接导入了
  
  pod 'SVProgressHUD'
  
  pod 'XYInfomationSection'
#  pod 'RealmSwift' 
  
end
