platform :ios, '10.0'

target 'YYUIKitDemo' do
  use_frameworks!

  # Pods for YYUIKitDemo
  pod 'MJExtension', '3.2.2'
  pod 'MJRefresh', '3.5.0'

  #pod 'LookinServer', :configurations => ['Debug']
  # pod 'TYAttributedLabel', '~> 2.6.2' // 网络上下不了，直接导入了
  pod 'XYInfomationSection'
  pod 'XYNav', :path => '/Users/quxiaoyou/Desktop/XYNav/'
  pod 'YYUIKit', :path => '../.'
  pod 'YYImage'

end
