platform :ios, '10.0'

#source 'http://gitlab.dev.zhaopin.com/b-mobile/ios-b-app-specs.git'

# 使用动态库
use_frameworks!

target 'XYUIKitDemo' do
  
  pod 'MJExtension', '3.2.2'
  pod 'MJRefresh', '3.5.0'

  pod 'SnapKit', '~> 5.0.0'
  
  # pod 'TYAttributedLabel', '~> 2.6.2' // 网络上下不了，直接导入了
  
  #pod 'SVProgressHUD'
  
  
  pod 'XYInfomationSection'#, '1.0.3'
#  pod 'RealmSwift'

  pod 'XYNav', :path => '/Users/quxiaoyou/Desktop/XYNav/'
  pod 'XYUIKit', :path => '../.'
#  pod 'XYNav'
end
